### ISSUE TITLE
Where can I find the SynologyDrive API documentation?

### ISSUE THREAD

**Issue by wittenator** [zbjdonald/synology-drive-api#1]
Hi zbjdonald,

thanks for taking up the task of creating a much needed wrapper for the Synology Drive!
While I was browsing the code, I wondered where you got the documentation for the Drive API from since I couldn't find it myself. Could you point me to the right direction?

Sincerely,
wittenator

**Comment by zbjdonald** [comment]
@wittenator Use Chrome Developer Tools to find api details. Open browser, login drive, press F12, click wanted action, check network and see API details.
