### ISSUE TITLE
Add OTP support

### ISSUE THREAD

**Issue by hendrikbl** [zbjdonald/synology-drive-api#10]
I have OTP enabled for my NAS wich leads to an Execption of type `otp` when attempting to create a `SynologyDrive` instance.

Are you planning on supporting OTP?

**Comment by zbjdonald** [comment]
em... DSM7 or DSM6?

**Comment by hendrikbl** [comment]
DSM 7

**Comment by axelperschmann** [comment]
facing the same issue. Any plans to support OTP soon?

**Comment by zbjdonald** [comment]
I got a dsm7 synology. I will try this weekend.

**Comment by zbjdonald** [comment]
@axelperschmann @hendrikbl Try 1.0.11

**Comment by axelperschmann** [comment]
Works now with 1.0.11, many thanks!

Only downside is, one has to provide the otp code with every single query (i.e. a new one every ~30 seconds). Is there a possibility to enter it once at the start of the session and then neglect it?

**Comment by zbjdonald** [comment]
```python
synd = SynologyDrive(NAS_USER, NAS_PASS, otp_code='XXXXXX')
synd.login()
synd.action1
synd.action2
synd.action3
synd.logout()
```

**Comment by hendrikbl** [comment]
Works like a charm 👍 thank you!
