### ISSUE TITLE
Overwriting when upload files

### ISSUE THREAD

**Issue by arthurier** [zbjdonald/synology-drive-api#12]
Hi! Thanks for the great work!

 In the original API there's argument `overwrite ` for **SYNO.FileStation.Upload** method. I am going to move my data from Google Sheets to Synology Office and have many scripts working with gsheets now. So if there's no option to work with osheet like with Gsheets API (inserting rows, lists, remove rows, e.t.c), I think I could manage all scripts to work inside excel and then reupload it in Synology with osheet format. But `.upload_file()` method creating new files in Drive instead of overwriting old ones with the same name.

Any help or advice? Thanks in advance

**Comment by zbjdonald** [comment]
Do mean reupload as osheet file type? Here's the process I understand:
1. Download 'hehe.osheet' as 'hehe.xlsx', do some work.
2. Upload 'hehe.xlsx' as 'hehe.osheet' and overwrite 'hehe.osheet'.

**Comment by arthurier** [comment]
Yes, correctly. But there's an argument in `convert_to_online_office` function _conflict_action_ which is default set by **rename**. And because of that if you have osheet with the same name, it will create new file "hehe(1).osheet". If you will set this argument _conflict_action_ to **version**, this will works well and will overwrite osheet document.

By the way, do you know, if it possible to edit inside osheet with API calls?

**Comment by arthurier** [comment]
So would be great if you will move this argument `conflict_action` for user to define

**Comment by zbjdonald** [comment]
Yes, I will pump a version to add 'conflict_action'. _"By the way, do you know, if it possible to edit inside osheet with API calls?"_ AFAIK, no way.

**Comment by arthurier** [comment]
Thank you!

**Comment by zbjdonald** [comment]
@fengdasuk19
