### ISSUE TITLE
I encountered exceptions when invoking each API

### ISSUE THREAD

**Issue by YimingLv** [zbjdonald/synology-drive-api#15]
like this：
raise SynologyException(
synology_drive_api.base.SynologyException: {"error":{"code":1000,"errors":{"line":107,"message":"list node failed"}},"success":false}

My Synology version is DSM 7.1-42661

**Comment by YimingLv** [comment]
Only the login and logout interfaces are working properly

**Comment by zbjdonald** [comment]
Check the file or folder path is correct, such as 'team-folders/test_drive/test.xls', 'mydrive/folder1/test.xls'.
