### ISSUE TITLE
请问DMS7在线osheet的转换下载，能加速吗？

### ISSUE THREAD

**Issue by 1983shake** [zbjdonald/synology-drive-api#21]
RT，我使用api下载一个在线osheet，大小60多MB，从开始下载，到下载完成（下载已转换后的xlsx文件的时间可以忽略），需要4分钟左右。所以请问作者能否加快文档的转换？我使用的是DS920+。谢谢。

**Comment by zbjdonald** [comment]
测试了一下，2MB 的 osheet 大概 5 秒钟转换，算起来时间差不多。你用的 920+ 不行的话上 M2 SSD （现在便宜）缓存，感觉osheet是存drive自己的db里面了，上固态可能提升点性能？转换 API 的话只有1个（目前用的），应该没有其他办法了。

**Comment by 1983shake** [comment]
> 测试了一下，2MB 的 osheet 大概 5 秒钟转换，算起来时间差不多。你用的 920+ 不行的话上 M2 SSD （现在便宜）缓存，感觉osheet是存drive自己的db里面了，上固态可能提升点性能？转换 API 的话只有1个（目前用的），应该没有其他办法了。

我用一个ssd的盘位的空间试了一下，60多MB，需要2分30秒左右，虽然有提升，可以值得一试。但还是希望官方能优化。谢谢

**Comment by zbjdonald** [comment]
官方优化估计不可能了哈哈，提了好多需求没一个实现的。我也是个苦命玩家呜呜。
