### ISSUE TITLE
Clarification about share Labels Instructions

### ISSUE THREAD

**Issue by dandreossi** [zbjdonald/synology-drive-api#26]
In the README.md you say

> If you want share labels between users, you should have access to these user accounts. Another solution is creating a tool user.

While it's clear the meaning of having the access to the user account I cannot understand what do you mean about the "tool user".
Is there some way, with some kind of tool_user, to share labels between users?
Can you help me?

**Comment by zbjdonald** [comment]
I have suggested a "share label" feature to the Synology development team, but there was no feedback. The meaning of "Tool User" is that all label operations are carried out through the tool user account. Anyone who wants to use labels needs to log in to the tool user's account. I have given up exploring the sharing of labels among multiple users.
