### ISSUE TITLE
team folder empty and list node failed with synd.list_folder

### ISSUE THREAD

**Issue by wailoktam** [zbjdonald/synology-drive-api#3]
Hi, Thanks for your good work. I have been using your library for a while but after someone reinstall the Synology NAS in my company. My code using your library no longer works and I cannot figure it out.  The major problem is no directories are visible to the library when creating or listing folders. 

I create a team folder called "apr" using the admin console. It is under /volume1/ when I login in the Synology Drive using ssh.
However, I get a {} when I try the synd.get_teamfolder_info() command. 

No matter what I put in the bracket of synd.list_folder(). I am getting the  list node failed with synd.list_folder error.
Some options I have tried are "/volume1", "volume1/apr". "/" gives me a permission error. 

 Any help would be greatly appreciated.

**Comment by zbjdonald** [comment]
Can you see your "apr" folder in drive web app? What's your drive server version? Does your account used in api has right permissions for "apr" folder?

**Comment by wailoktam** [comment]
Thanks for your reply. I discover that I need to turn on sync in the admin control  console  in order for the api to see the team folder. There is however a new issue with destination folder when using the upload command. 

The path name of the source file will be concatenated to the destination folder value. It would be great if you can look into it. I get around by doing some string operation to remove the unnecessary part of the path name between the line mentioning the filename of the source file and the line doing the uploading.
