### ISSUE TITLE
it does not appear as though DSM 7 is supported

### ISSUE THREAD

**Issue by shersch** [zbjdonald/synology-drive-api#4]
it looks like I need to pass in the "version" when logging in, but I'm not certain.  I think that's why I'm not having much success with this.

**Comment by zbjdonald** [comment]
I have no DSM 7. You can try change params variable in [login](https://github.com/zbjdonald/synology-drive-api/blob/24f6ef2d67d4561193c0b6ef9fbd2f355b968c9e/synology_drive_api/base.py#L204) and [logout](https://github.com/zbjdonald/synology-drive-api/blob/24f6ef2d67d4561193c0b6ef9fbd2f355b968c9e/synology_drive_api/base.py#L221) `{'version': '2'}` => `{'version': '3'}`. 
[DSM 7 - API Support | Synology Community](https://community.synology.com/enu/forum/20/post/139113)

**Comment by shersch** [comment]
that worked!  thanks!
