### ISSUE TITLE
dsm_version parameter not working

### ISSUE THREAD

**Issue by schulz** [zbjdonald/synology-drive-api#5]
Hi,

`dsm_version` parameter is not accepted by `SynologyDrive` class and is not passed to `SynologySession`. `SynologySession` `dsm_version` default value is 6 thus the documentation description is wrong, please update the code.

**Comment by zbjdonald** [comment]
I'll check it tomorrow.

**Comment by wellsleep** [comment]
same problem encountered. 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_106/412349273.py in <module>
----> 1 with SynologyDrive(NAS_USER, NAS_PASS, NAS_IP, dsm_version='7') as synd:
      2     pass

TypeError: __init__() got an unexpected keyword argument 'dsm_version'
```

**Comment by zbjdonald** [comment]
@wellsleep I'll fix it on Monday.

**Comment by zbjdonald** [comment]
@schulz @wellsleep You can try 1.0.6.

**Comment by wellsleep** [comment]
1.0.6 worked!

**Comment by schulz** [comment]
@zbjdonald it works, thank you!
