### ISSUE TITLE
Move file to other folder

### ISSUE THREAD

**Issue by h-teske** [zbjdonald/synology-drive-api#9]
Hi, I really love your work and it helps me a lot.

I'm trying to move a file to a different folder. In your sourcecode I see a comment 

`        move file or folder to another folder
`
Is this implemented yet and I just fail to use it or is this still a todo?

Many thanks again!

**Comment by zbjdonald** [comment]
Hi, it was implemented. I use it in production. `synd_admin.move_path(file_info['file_id'], 'team-folders/folder1/folder2')`.

**Comment by h-teske** [comment]
ah perfect, that worked. many thanks for the quick help!
